import { KeywordType } from '@guardian/content-api-models/v1/keywordType';
import type { Tag } from '@guardian/content-api-models/v1/tag';
import { TagType } from '@guardian/content-api-models/v1/tagType';

export const filterTagsUS: Tag[] = [
	{
		id: 'thefilter-us/series/thefilter-us',
		type: TagType.SERIES,
		sectionId: 'thefilter-us',
		sectionName: 'The Filter US',
		webTitle: 'The Filter US',
		webUrl: 'https://www.theguardian.com/thefilter-us/series/thefilter-us',
		apiUrl: 'https://content.guardianapis.com/thefilter-us/series/thefilter-us',
		references: [],
		description:
			'\u003Cp\u003EIndependent product reviews, trustworthy buying advice and sustainable shopping ideas from the Guardian&nbsp,\u003C/p\u003E',
		internalName: 'The Filter US (series tag)',
	},
	{
		id: 'lifeandstyle/lifeandstyle',
		type: TagType.KEYWORD,
		sectionId: 'lifeandstyle',
		sectionName: 'Life and style',
		webTitle: 'Life and style',
		webUrl: 'https://www.theguardian.com/lifeandstyle/lifeandstyle',
		apiUrl: 'https://content.guardianapis.com/lifeandstyle/lifeandstyle',
		references: [
			{
				id: 'rich-link/ https://www.theguardian.com/info/2020/mar/25/the-guide-staying-in-sign-up-for-our-home-entertainment-tips',
				type: 'rich-link',
			},
		],
		internalName: 'Life and style',
		keywordType: KeywordType.OTHER,
	},
	{
		id: 'campaign/email/the-filter-us',
		type: TagType.CAMPAIGN,
		webTitle: 'The Filter US (newsletter signup)',
		webUrl: 'https://www.theguardian.com/campaign/email/the-filter-us',
		apiUrl: 'https://content.guardianapis.com/campaign/email/the-filter-us',
		references: [],
		campaignInformationType: 'email',
		internalName: 'The Filter US (newsletter signup)',
	},
	{
		id: 'lifeandstyle/homes',
		type: TagType.KEYWORD,
		sectionId: 'lifeandstyle',
		sectionName: 'Life and style',
		webTitle: 'Homes',
		webUrl: 'https://www.theguardian.com/lifeandstyle/homes',
		apiUrl: 'https://content.guardianapis.com/lifeandstyle/homes',
		references: [
			{
				id: 'rich-link/https://www.theguardian.com/lifeandstyle/2020/sep/09/design-review-get-the-newsletter-for-the-way-we-live-now',
				type: 'rich-link',
			},
		],
		internalName: 'Homes (Life and style)',
		keywordType: KeywordType.OTHER,
	},
	{
		id: 'tone/features',
		type: TagType.TONE,
		webTitle: 'Features',
		webUrl: 'https://www.theguardian.com/tone/features',
		apiUrl: 'https://content.guardianapis.com/tone/features',
		references: [],
		internalName: 'Feature (Tone)',
	},
	{
		id: 'type/article',
		type: TagType.TYPE,
		webTitle: 'Article',
		webUrl: 'https://www.theguardian.com/articles',
		apiUrl: 'https://content.guardianapis.com/type/article',
		references: [],
		internalName: 'Article (Content type)',
	},
	{
		id: 'tone/reviews',
		type: TagType.TONE,
		webTitle: 'Reviews',
		webUrl: 'https://www.theguardian.com/tone/reviews',
		apiUrl: 'https://content.guardianapis.com/tone/reviews',
		references: [],
		internalName: 'Review (Tone)',
	},
	{
		id: 'profile/tobey-grumet-segal',
		type: TagType.CONTRIBUTOR,
		webTitle: 'Tobey Grumet Segal',
		webUrl: 'https://www.theguardian.com/profile/tobey-grumet-segal',
		apiUrl: 'https://content.guardianapis.com/profile/tobey-grumet-segal',
		references: [],
		bio: '\u003Cp\u003ETobey Grumet Segal is a freelance lifestyle and tech journalist with more than 20 years of experience writing and editing.\u003C/p\u003E',
		firstName: 'Tobey',
		lastName: 'Segal',
		r2ContributorId: '100788',
		internalName: 'Tobey Grumet Segal',
	},
	{
		id: 'tracking/commissioningdesk/filter-us',
		type: TagType.TRACKING,
		webTitle: 'The Filter US',
		webUrl: 'https://www.theguardian.com/tracking/commissioningdesk/filter-us',
		apiUrl:
			'https://content.guardianapis.com/tracking/commissioningdesk/filter-us',
		references: [],
		internalName: 'Filter US (commissioning)',
	},
	{
		id: 'tracking/commissioningdesk/us-filter-product-reviews',
		type: TagType.TRACKING,
		webTitle: 'US Filter product reviews',
		webUrl:
			'https://www.theguardian.com/tracking/commissioningdesk/us-filter-product-reviews',
		apiUrl:
			'https://content.guardianapis.com/tracking/commissioningdesk/us-filter-product-reviews',
		references: [],
		internalName: 'US Filter product reviews',
	},
];

export const filterTagsUK: Tag[] = [
	{
		id: 'thefilter/series/the-filter',
		type: TagType.SERIES,
		sectionId: 'thefilter',
		sectionName: 'The Filter',
		webTitle: 'The Filter',
		webUrl: 'https://www.theguardian.com/thefilter/series/the-filter',
		apiUrl: 'https://content.guardianapis.com/thefilter/series/the-filter',
		references: [],
		description:
			'\u003Cp\u003EThe Filter is the Guardian’s home for independent product reviews and recommendations. The team tests the best fashion, beauty, food, tech, appliances, lifestyle items, sustainable products and more. You can trust our journalists and experts to give the best shopping advice\u003C/p\u003E',
		internalName: 'The Filter UK (series tag)',
	},
	{
		id: 'lifeandstyle/lifeandstyle',
		type: TagType.KEYWORD,
		sectionId: 'lifeandstyle',
		sectionName: 'Life and style',
		webTitle: 'Life and style',
		webUrl: 'https://www.theguardian.com/lifeandstyle/lifeandstyle',
		apiUrl: 'https://content.guardianapis.com/lifeandstyle/lifeandstyle',
		references: [
			{
				id: 'rich-link/ https://www.theguardian.com/info/2020/mar/25/the-guide-staying-in-sign-up-for-our-home-entertainment-tips',
				type: 'rich-link',
			},
		],
		internalName: 'Life and style',
		keywordType: KeywordType.OTHER,
	},
	{
		id: 'campaign/email/the-filter',
		type: TagType.CAMPAIGN,
		webTitle: 'The Filter (newsletter signup)',
		webUrl: 'https://www.theguardian.com/campaign/email/the-filter',
		apiUrl: 'https://content.guardianapis.com/campaign/email/the-filter',
		references: [],
		campaignInformationType: 'email',
		internalName: 'The Filter UK (newsletter signup)',
	},
	{
		id: 'fashion/fashion',
		type: TagType.KEYWORD,
		sectionId: 'fashion',
		sectionName: 'Fashion',
		webTitle: 'Fashion',
		webUrl: 'https://www.theguardian.com/fashion/fashion',
		apiUrl: 'https://content.guardianapis.com/fashion/fashion',
		references: [
			{
				id: 'rich-link/https://www.theguardian.com/info/ng-interactive/2017/jul/25/sign-up-for-the-fashion-statement-email',
				type: 'rich-link',
			},
		],
		internalName: 'Fashion',
		keywordType: KeywordType.OTHER,
	},
	{
		id: 'lifeandstyle/homes',
		type: TagType.KEYWORD,
		sectionId: 'lifeandstyle',
		sectionName: 'Life and style',
		webTitle: 'Homes',
		webUrl: 'https://www.theguardian.com/lifeandstyle/homes',
		apiUrl: 'https://content.guardianapis.com/lifeandstyle/homes',
		references: [
			{
				id: 'rich-link/https://www.theguardian.com/lifeandstyle/2020/sep/09/design-review-get-the-newsletter-for-the-way-we-live-now',
				type: 'rich-link',
			},
		],
		internalName: 'Homes (Life and style)',
		keywordType: KeywordType.OTHER,
	},
	{
		id: 'fashion/beauty',
		type: TagType.KEYWORD,
		sectionId: 'fashion',
		sectionName: 'Fashion',
		webTitle: 'Beauty',
		webUrl: 'https://www.theguardian.com/fashion/beauty',
		apiUrl: 'https://content.guardianapis.com/fashion/beauty',
		references: [],
		internalName: 'Beauty',
		keywordType: KeywordType.OTHER,
	},
	{
		id: 'fashion/dresses',
		type: TagType.KEYWORD,
		sectionId: 'fashion',
		sectionName: 'Fashion',
		webTitle: 'Dresses',
		webUrl: 'https://www.theguardian.com/fashion/dresses',
		apiUrl: 'https://content.guardianapis.com/fashion/dresses',
		references: [],
		internalName: 'Dresses (Fashion)',
		keywordType: KeywordType.OTHER,
	},
	{
		id: 'fashion/skirts',
		type: TagType.KEYWORD,
		sectionId: 'fashion',
		sectionName: 'Fashion',
		webTitle: 'Skirts',
		webUrl: 'https://www.theguardian.com/fashion/skirts',
		apiUrl: 'https://content.guardianapis.com/fashion/skirts',
		references: [],
		internalName: 'Skirts (Fashion)',
		keywordType: KeywordType.OTHER,
	},
	{
		id: 'food/ice-cream',
		type: TagType.KEYWORD,
		sectionId: 'food',
		sectionName: 'Food',
		webTitle: 'Ice-cream and sorbet',
		webUrl: 'https://www.theguardian.com/food/ice-cream',
		apiUrl: 'https://content.guardianapis.com/food/ice-cream',
		references: [],
		internalName: 'Ice-cream and sorbet',
		keywordType: KeywordType.OTHER,
	},
	{
		id: 'fashion/mens-hair',
		type: TagType.KEYWORD,
		sectionId: 'fashion',
		sectionName: 'Fashion',
		webTitle: "Men's hair",
		webUrl: 'https://www.theguardian.com/fashion/mens-hair',
		apiUrl: 'https://content.guardianapis.com/fashion/mens-hair',
		references: [],
		internalName: 'Hair (Men)',
		keywordType: KeywordType.OTHER,
	},
	{
		id: 'fashion/womens-hair',
		type: TagType.KEYWORD,
		sectionId: 'fashion',
		sectionName: 'Fashion',
		webTitle: "Women's hair",
		webUrl: 'https://www.theguardian.com/fashion/womens-hair',
		apiUrl: 'https://content.guardianapis.com/fashion/womens-hair',
		references: [],
		internalName: 'Hair (Women)',
		keywordType: KeywordType.OTHER,
	},
	{
		id: 'lifeandstyle/hair-care',
		type: TagType.KEYWORD,
		sectionId: 'lifeandstyle',
		sectionName: 'Life and style',
		webTitle: 'Hair care',
		webUrl: 'https://www.theguardian.com/lifeandstyle/hair-care',
		apiUrl: 'https://content.guardianapis.com/lifeandstyle/hair-care',
		references: [],
		internalName: 'Hair care',
		keywordType: KeywordType.OTHER,
	},
	{
		id: 'fashion/mens-tops',
		type: TagType.KEYWORD,
		sectionId: 'fashion',
		sectionName: 'Fashion',
		webTitle: "Men's tops",
		webUrl: 'https://www.theguardian.com/fashion/mens-tops',
		apiUrl: 'https://content.guardianapis.com/fashion/mens-tops',
		references: [],
		internalName: "Men's tops (Fashion)",
		keywordType: KeywordType.OTHER,
	},
	{
		id: 'food/tea',
		type: TagType.KEYWORD,
		sectionId: 'food',
		sectionName: 'Food',
		webTitle: 'Tea',
		webUrl: 'https://www.theguardian.com/food/tea',
		apiUrl: 'https://content.guardianapis.com/food/tea',
		references: [],
		internalName: 'Tea',
		keywordType: KeywordType.OTHER,
	},
	{
		id: 'food/coffee',
		type: TagType.KEYWORD,
		sectionId: 'food',
		sectionName: 'Food',
		webTitle: 'Coffee',
		webUrl: 'https://www.theguardian.com/food/coffee',
		apiUrl: 'https://content.guardianapis.com/food/coffee',
		references: [],
		internalName: 'Coffee',
		keywordType: KeywordType.OTHER,
	},
	{
		id: 'travel/travel',
		type: TagType.KEYWORD,
		sectionId: 'travel',
		sectionName: 'Travel',
		webTitle: 'Travel',
		webUrl: 'https://www.theguardian.com/travel/travel',
		apiUrl: 'https://content.guardianapis.com/travel/travel',
		references: [],
		internalName: 'Travel',
		keywordType: KeywordType.OTHER,
	},
	{
		id: 'tone/features',
		type: TagType.TONE,
		webTitle: 'Features',
		webUrl: 'https://www.theguardian.com/tone/features',
		apiUrl: 'https://content.guardianapis.com/tone/features',
		references: [],
		internalName: 'Feature (Tone)',
	},
	{
		id: 'type/article',
		type: TagType.TYPE,
		webTitle: 'Article',
		webUrl: 'https://www.theguardian.com/articles',
		apiUrl: 'https://content.guardianapis.com/type/article',
		references: [],
		internalName: 'Article (Content type)',
	},
	{
		id: 'tone/best-ofs',
		type: TagType.TONE,
		webTitle: 'Best of',
		webUrl: 'https://www.theguardian.com/tone/best-ofs',
		apiUrl: 'https://content.guardianapis.com/tone/best-ofs',
		references: [],
		internalName: 'Best of (tone)',
	},
	{
		id: 'profile/jane-hoskyn',
		type: TagType.CONTRIBUTOR,
		webTitle: 'Jane Hoskyn',
		webUrl: 'https://www.theguardian.com/profile/jane-hoskyn',
		apiUrl: 'https://content.guardianapis.com/profile/jane-hoskyn',
		references: [],
		bio: '\u003Cp\u003EJane Hoskyn is a freelance consumer journalist with three decades of experience. Her work has made her an expert in all manner of consumables, from sports watches to solar panels\u003C/p\u003E',
		bylineImageUrl: 'https://uploads.guim.co.uk/2024/10/18/Jane_Hoskyn.jpg',
		bylineLargeImageUrl:
			'https://uploads.guim.co.uk/2024/10/18/Jane_Hoskyn.png',
		firstName: 'Jane',
		lastName: 'Hoskyn',
		r2ContributorId: '97933',
		internalName: 'Jane Hoskyn',
	},
	{
		id: 'tracking/commissioningdesk/the-filter',
		type: TagType.TRACKING,
		webTitle: 'The Filter UK',
		webUrl: 'https://www.theguardian.com/tracking/commissioningdesk/the-filter',
		apiUrl:
			'https://content.guardianapis.com/tracking/commissioningdesk/the-filter',
		references: [],
		internalName: 'The Filter UK (commissioning)',
	},
	{
		id: 'tracking/commissioningdesk/shopping-feature',
		type: TagType.TRACKING,
		webTitle: 'Shopping feature',
		webUrl:
			'https://www.theguardian.com/tracking/commissioningdesk/shopping-feature',
		apiUrl:
			'https://content.guardianapis.com/tracking/commissioningdesk/shopping-feature',
		references: [],
		internalName: 'Shopping feature (The Filter)',
	},
	{
		id: 'tracking/audience/uk',
		type: TagType.TRACKING,
		webTitle: 'UK',
		webUrl: 'https://www.theguardian.com/tracking/audience/uk',
		apiUrl: 'https://content.guardianapis.com/tracking/audience/uk',
		references: [],
		internalName: 'UK',
	},
];

export const nonFilterTags: Tag[] = [
	{
		id: 'football/football',
		type: TagType.KEYWORD,
		sectionId: 'football',
		sectionName: 'Football',
		webTitle: 'Football',
		webUrl: 'https://www.theguardian.com/football/football',
		apiUrl: 'https://content.guardianapis.com/football/football',
		references: [],
		internalName: 'Football',
		keywordType: KeywordType.OTHER,
	},
];
